#!/usr/bin/env bash
set -e

this_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export COVERAGE_PROCESS_START="${this_dir}/.coveragerc"
export PYTHONPATH="${this_dir}/coverage_sitecustomize:$PYTHONPATH"

find . -name '*.pyc' -delete
coverage erase
rm -rf "$this_dir/.coverage.*"
python -m unittest discover -s test -p '*.py'
# coverage combine
# coverage report
